name: oliverbray
favicon: null
layout_spectrum: 0.62826
typography_spectrum: 0.90937
title: Oliver Bray
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8a88e'
    - '#633818'
    - '#a88f67'
    - '#590e12'
    - '#846838'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
