name: oliverbray
favicon: null
layout_spectrum: 0.69739
typography_spectrum: 0.46543
title: Oliver Bray
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffa570'
    - '#000000'
    - '#ff1724'
    - '#b97851'
    - '#412a1c'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
