name: oliverbray
favicon: null
layout_spectrum: 0.24778
typography_spectrum: 0.26459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#feccff'
    - '#000000'
    - '#808080'
    - '#4e504e'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
